"""Access Code table

Revision ID: 62508ed98fbe
Revises: 005597200fa9
Create Date: 2019-03-27 17:09:48.612029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62508ed98fbe'
down_revision = '005597200fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('user_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_code_access_code'), 'access_code', ['access_code'], unique=True)
    op.create_index(op.f('ix_access_code_email'), 'access_code', ['email'], unique=True)
    op.create_index(op.f('ix_access_code_user_type'), 'access_code', ['user_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_code_user_type'), table_name='access_code')
    op.drop_index(op.f('ix_access_code_email'), table_name='access_code')
    op.drop_index(op.f('ix_access_code_access_code'), table_name='access_code')
    op.drop_table('access_code')
    # ### end Alembic commands ###
