"""new user type in user table

Revision ID: c4554693b9d6
Revises: 62508ed98fbe
Create Date: 2019-04-02 11:27:27.693532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4554693b9d6'
down_revision = '62508ed98fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_code_user_type', table_name='access_code')
    op.drop_index('ix_user_user_type', table_name='user')
    op.create_index(op.f('ix_user_user_type'), 'user', ['user_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_type'), table_name='user')
    op.create_index('ix_user_user_type', 'user', ['user_type'], unique=1)
    op.create_index('ix_access_code_user_type', 'access_code', ['user_type'], unique=False)
    # ### end Alembic commands ###
